name: CICD

on:
    push:
        branches: [anix]

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}

            - name: Build docker image
              run: docker build -t barcafan830/nodejs-app

            - name: Publish image to docker hub
              run: docker push barcafan830/nodejs-app:latest


    deploy:
        needs: build

        runs-on: self-hosted


              
